services:
  backend:
    build:
      context: ./tribeX-hris-auth-api
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./tribeX-hris-auth-api/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend/blues-clues-hris-frontend-web
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:5000/api/tribeX/auth/v1
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000/api/tribeX/auth/v1
    depends_on:
      - backend
    ports:
      - "3000:3000"
