sonar.projectKey=blues-clues-frontend
sonar.projectName=Blues Clues HRIS Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=squ_f394e742be847baef09fa97b2a42f571c8e16057
